server:
  port: 8080
spring:
  application.name: ${APPLICATION_NAME:cloud-storage}
amazon:
  s3:
    host: ${S3_HOST:http://localhost:9000}
    region: ${S3_REGION:}
    access-key: ${S3_ACCESS_KEY:}
    secret-key: ${S3_SECRET_KEY:}
    default-bucket: ${S3_DEFUALT_BUCKET:default.bucket}